language: php

sudo: false

services: [rabbitmq]

addons:
  apt:
    packages:
    - cmake
    - rabbitmq-server

env:
    global:
        - LIBRABBITMQ_VERSION=v0.8.0
        - PHPAMQP_VERSION=v1.9.4

matrix:
    include:
        # Test with default configuration
        - { php: 7.2 }
        - { php: 7.3 }
        # Test against librabbitmq cutting-edge
        - { php: 7.2, env: LIBRABBITMQ_VERSION=master }
        # Test with lowest & beta dependencies
        - { php: 7.1, env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' }
        - { php: 7.3, env: DEPENDENCIES=beta }

    fast_finish: true

before_install:
  - if [ "$DEPENDENCIES" == "beta" ]; then composer config minimum-stability beta; fi;

install:
  - composer update --prefer-dist --no-progress --no-suggest $COMPOSER_FLAGS --ansi
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo env "PATH=$PATH" ./tests/bin/prepare_rabbit.sh

script:
    - ./vendor/bin/phpunit
