language: php

sudo: false

services: [rabbitmq]

addons:
    apt:
        packages:
            - cmake
            - rabbitmq-server

env:
    global:
        - LIBRABBITMQ_VERSION=v0.8.0
        - PHPAMQP_VERSION=v1.9.4

matrix:
    fast_finish: true
    include:
        - php: 7.4
        - php: 8.0

        # Test against librabbitmq cutting-edge
        - { php: 8.1, env: LIBRABBITMQ_VERSION=master }

        # Force some major versions of Symfony
        - php: 7.4
          env: SYMFONY_VERSION="3.*"
        - php: 7.4
          env: SYMFONY_VERSION="4.*"
        - php: 7.4
          env: SYMFONY_VERSION="5.*"
        - php: 8.0
          env: SYMFONY_VERSION="3.*"
        - php: 8.0
          env: SYMFONY_VERSION="4.*"
        - php: 8.0
          env: SYMFONY_VERSION="5.*"
        - php: 8.0
          env: SYMFONY_VERSION="6.*"

        # Test with latest PHP version & beta dependencies
        - { php: 8.1, env: STABILITY=dev }

    allow_failures:
        - { php: 8.1, env: STABILITY=dev }
        - { php: 8.1, env: LIBRABBITMQ_VERSION=master }

before_install:
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

install:
    - composer update --prefer-dist --no-progress --no-suggest $COMPOSER_FLAGS --ansi
    - sudo rabbitmq-plugins enable rabbitmq_management
    - sudo env "PATH=$PATH" ./tests/bin/prepare_rabbit.sh

script:
    - ./vendor/bin/phpunit
