on: [pull_request]

name: Static analysis

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: amqp
          coverage: none

      - name: Install php-cs-fixer
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--working-dir=tools/php-cs-fixer"

      - name: PHP-CS-Fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.dist.php

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: amqp
          coverage: none

      - name: Download dependencies
        uses: ramsey/composer-install@v3

      - name: Install PHPStan
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--working-dir=tools/phpstan"

      - name: PHPStan
        run: tools/phpstan/vendor/bin/phpstan analyze --no-progress --error-format=checkstyle
